### ISSUE TITLE
Testando env

### ISSUE THREAD

**Issue by rodrigondec** [imobanco/WooCommerce-Imobanco#14]
# Resumo
Relacionado ao épico #13 

Precisamos testar as configurações do plugin.

# A injeção dos envs estão funcionando?

## Checklist
- [x] 'WOO_IMOPAY_ENVIRONMENT' (test ou prod)
- [x] 'WOO_IMOPAY_SELLER_ID' (id do seller dono do ecommerce)
- [x] 'WOO_IMOPAY_API_KEY' (chave de acesso)

**Comment by PedroRegisPOAR** [comment]
## Resumo 

Para resolver essa issue tive que adicionar no `.env.example` as variaveis de ambiente que o pluigin precisa:
```
WOO_IMOPAY_ENVIRONMENT=test1
WOO_IMOPAY_SELLER_ID=test2
WOO_IMOPAY_API_KEY=test3
```

## Provas

Seguir as intruções em [README.md do Ecommerce](https://github.com/imobanco/Ecommerce/tree/feature/testar-plugin-de-pagamento#novas-instru%C3%A7%C3%B5es-para-uso) e rodar:

``` bash
$ make bash.exec
I have no name!@5d700824f577:/$ echo -e "$WOO_IMOPAY_ENVIRONMENT \n $WOO_IMOPAY_SELLER_ID \n $WOO_IMOPAY_API_KEY"
```

![issue-13](https://user-images.githubusercontent.com/20312381/90282422-b0963d80-de44-11ea-818b-01426e08ffc2.png)

**Comment by rodrigondec** [comment]
@Raidro estando em variável de ambiente, o `getenv` pega corretamente? Acredito que só falta isso para fechar essa issue

**Comment by Raidro** [comment]
> @Raidro estando em variável de ambiente, o `getenv` pega corretamente? Acredito que só falta isso para fechar essa issue

Isso no PHP ? se for, sim, vc da um `getenv('NOME_DA_VARIAVEL')`
