### ISSUE TITLE
Testando transação

### ISSUE THREAD

**Issue by rodrigondec** [imobanco/WooCommerce-Imobanco#17]
# Resumo
Relacionado ao épico #13.

Precisamos testar a parte de pedido cadastrando transaction no imopay!

# Outputs
Todos os testes precisam ser documentados nessa issue como um novo comentário da seguinte forma:

```
# Nome do teste
## Considerações
alguma consideração dos testadores caso tenha

## Prints
file_upload1
.
.
.
file_uploadn
``` 

Na sessão `## Prints` quero:
- foto da interface do usuário na loja mostrando o peido
- foto do wp-admin do pedido criado (com seus dados)
- foto do django admin com as infos do transaction/payment_method (2 fotos para boleto)
- foto do dbeaver mostrando o `id_imopay` do usuário da loja (caso seja possível ver isso no wp-admin, mostrar no wp-admin)

# 1. Criação de transação cartão presente
Dado que já existem:
  - um usuário u_loja1 na loja
  - um buyer b_imo1 para u_loja1 no imopay
  - endereço e_loja1 na loja
  - endereço e_imo1 no imopay para b_imo1
  - produto pr_loja1 na loja

Quando u_loja1 comprar pr_loja1 no cartão corretamente
Então deve:
  - existir um pedido pe_loja1 woocommerce
  - existir uma transação t_imo1 no imopay com:
    - t_imo1.amount == pr_loja1.valor_do_produto
    - t_imo1.description == '{Nome da loja} - Pedido no cartão de crédito'
    - t_imo1.payer == b_imo1
    - t_imo1.receiver == {SELLER_ID do ecommerce configurado no plugin}
  - pe_loja1.status == ['wc-pending'](https://github.com/ibrunodev/WooCommerce-Imobanco/blob/465bb9eaeaad529cbb8ac881b6c2cb93fbe90627/woocommerce-imobanco/includes/api.php#L30)

## Checklist
- [x] criação de transação cartão presente

# 1.5 Criação de transação cartão presente CHAOS MONKEY
Utilizem a criatividade de vocês para fazer o cenário respectivo falhar e retornar erros!

Eu quero provas e que vocês consigam quebrar algo.

Caso não consigam quebrar, basta documentar os cenários e fotos das mensagens de erro exibidas para vocês.

## Checklist
- [ ] criação de transação cartão presente CHAOS MONKEY

# 2. Criação de transação boleto
Dado que já existem:
  - um usuário u_loja1 na loja
  - um buyer b_imo1 para u_loja1 no imopay
  - endereço e_loja1 na loja
  - endereço e_imo1 no imopay para b_imo1
  - produto pr_loja1 na loja

Quando u_loja1 comprar pr_loja1 no boleto corretamente
Então deve:
  - existir um pedido pe_loja1 woocommerce
  - existir um boleto i_imo1 no imopay com:
    - data de expiração
    - data limite
  - existir uma transação t_imo1 no imopay com:
    - t_imo1.amount == pr_loja1.valor_do_produto
    - t_imo1.description == '{Nome da loja} - Pedido no boleto'
    - t_imo1.payer == b_imo1
    - t_imo1.receiver == {SELLER_ID do ecommerce configurado no plugin}
    - t_imo1.payment_method == i_imo1
  - pe_loja1.status == ['wc-pending'](https://github.com/ibrunodev/WooCommerce-Imobanco/blob/465bb9eaeaad529cbb8ac881b6c2cb93fbe90627/woocommerce-imobanco/includes/api.php#L30)

## Checklist
- [x] criação de transação boleto

# 2.5 Criação de transação boleto CHAOS MONKEY
Utilizem a criatividade de vocês para fazer o cenário respectivo falhar e retornar erros!

Eu quero provas e que vocês consigam quebrar algo.

Caso não consigam quebrar, basta documentar os cenários e fotos das mensagens de erro exibidas para vocês.

## Checklist
- [ ] criação de transação boleto CHAOS MONKEY

**Comment by Raidro** [comment]
# Teste transação cartão presente

## Considerações

- A transação deu `erro 500`
- Não foi criado uma transação no `imopay_api`
- A transação foi cadastrada no `woocommerce` corretamente
- No `dbeaver` consta o item comprado
- 2 `métodos de pagamento` com o mesmo nome e 1 deles não possui nenhuma informação 


## Prints

- Com um usuário previamente criado, com endereço corretamente cadastrado, vamos então acessar a loja pela url: `localhost` e realizar a compra da faca Karambit

- na tela de carrinho ( ` localhost/carrinho `) vamos então fechar a compra e prosseguir pra próxima tela

- na tela de finalizar compra (`localhost/finalizar-compra`) vamos então preencher tudo que dor necessário e finalizar a compra selecionando o método de pagamento `cartão`:

![transacao_finalizada](https://user-images.githubusercontent.com/16165385/90985842-e928cc00-e554-11ea-9776-fddd2eb6f634.png)

![detalhe_do_pedido](https://user-images.githubusercontent.com/16165385/90985863-08bff480-e555-11ea-8ae9-e509e753dbb6.png)


- A compra foi finalizada corretamente, vamos agora olhar no `minha conta` se consta o registro da compra

- no `minha conta`  no menu lateral esquerdo, vamos clicar em pedidos

![pedido_minha_conta](https://user-images.githubusercontent.com/16165385/90985882-20977880-e555-11ea-8f0c-90823893013c.png)

- O pedido consta corretamente

- vamos então, clicar em `visualizar` para ver os detalhes do pedido

![detalhes_pedido](https://user-images.githubusercontent.com/16165385/90985901-3c9b1a00-e555-11ea-8779-4a79430b1b9d.png)

- Detalhes estão corretos

- agora, vamos olhar no `imopay_api` se uma `transação` foi cadastrada com sucesso 

![transacao_inexistente](https://user-images.githubusercontent.com/16165385/90985916-648a7d80-e555-11ea-8031-24c431cb7b4b.png)

- nenhuma `transação` foi registrada

- vamos então olhar os `logs` do `imopay_api` 

![traceback](https://user-images.githubusercontent.com/16165385/90986011-30fc2300-e556-11ea-93fd-fd54cefb735f.png)

- Um erro ocorreu durante a transação com `status 500` e deu um `traceback`

- vamos então olhar os `logs` do `ecommerce`

![console_debug](https://user-images.githubusercontent.com/16165385/90986029-58eb8680-e556-11ea-8e4f-74cf5b0d843f.png)

- Ocorreu um erro na transaçao com `status 500` na url `transations/create_card_present_transation/`

- vamos olhar no `dbeaver` se o produto existe

![product_dbeaver](https://user-images.githubusercontent.com/16165385/90986077-a4059980-e556-11ea-81be-08e45d097c13.png)

- O produto consta no `dbeaver`

# OBS

- ao ir pra tela de `finalizar-compra`  e escolher o `método de pagamento` vemos que existem 2 métodos com o mesmo nome `custom payment` aonde 1 deles possui o cadastro do cartão para pagamento com `cartão` e o outro não possui informação nenhuma:

- método de pagamento do cartão
 
![2payment](https://user-images.githubusercontent.com/16165385/90986183-2ee69400-e557-11ea-810b-0ee4407fe99e.png)

- o outro `payment method`

![mesmo_nome](https://user-images.githubusercontent.com/16165385/90986231-93a1ee80-e557-11ea-83a0-c6bd357febff.png)

**Comment by Raidro** [comment]
# Teste transação  boleto

## Considerações

- Ao `finalizar a compra` o boleto é gerado com sucesso
- No `minha conta` o boleto consta corretamente
- No `dbeaver` o produto esta cadastrado corretamente
- Foi criado no `invoice` do `imopay_api` o boleto
- Foi criado no `transaction` do `imopay_api` a `transação boleto`

## obs do testador
- O primeiro teste com a `Transação boleto` foi realizado com o valor do produto em `R$ 3000,00` entretanto, foi gerado um erro 
```
"Request URL":"django":8000/transactions/create_invoice_transaction/ - Method:"post - Response":{
   "non_field_errors":"There was an error generating the boleto. The error was: Invalid value fields ['Amount is more than limit']",
   "status_code":400
```
- acredito então, que exista um limite de valor para `transação boleto`.
- Um novo teste foi então realizado diminuindo o valor para `R$300,00` e com esse valor a `transação boleto` foi completada com sucesso

# Prints

- Com um usuário previamente criado, com endereço corretamente cadastrado, vamos então acessar a loja pela url: `localhost` e realizar a compra da faca Karambit

- na tela de carrinho (`localhost/carrinho`) vamos então fechar a compra e prosseguir pra próxima tela

- na tela de finalizar compra (`localhost/finalizar-compra`) vamos então preencher tudo que dor necessário e finalizar a compra selecionando o método de pagamento `boleto`:

![opço boleto](https://user-images.githubusercontent.com/16165385/90990112-1d13e980-e575-11ea-9a06-6a768cd654b6.png)

![compra_finalizada](https://user-images.githubusercontent.com/16165385/90990116-256c2480-e575-11ea-89e6-076dd9cdeef4.png)

- Compra finalizada com sucesso

![boleto gerado](https://user-images.githubusercontent.com/16165385/90990132-42085c80-e575-11ea-9a8e-75cef14e961e.png)

![boleto_gerado](https://user-images.githubusercontent.com/16165385/90990134-46cd1080-e575-11ea-9c69-3aff2033e1d6.png)

![detalhe do pedido](https://user-images.githubusercontent.com/16165385/90990138-4cc2f180-e575-11ea-8742-79440a26aacb.png)

- como pode ser visto, `boleto` foi gerado com sucesso e as informações de `detalhes` estão corretas

- vamos então verificar no `minha conta`  se o pedido está corretamente cadastrado lá

![minha conta_criada_pedido](https://user-images.githubusercontent.com/16165385/90990153-83007100-e575-11ea-8112-35d209ff1717.png)

- pedido devidamente cadastrado (o pedido é o de 300 reais)

- vamos olhar os detalhes do pedido

![detalhe minha conta criada](https://user-images.githubusercontent.com/16165385/90990167-97446e00-e575-11ea-9ada-9e221180f04c.png)

- informações do ` detalhe` conferem

- vamos agora olhar no `imopay_api`  se o `invoice` foi criado corretamente

![invoice_criado](https://user-images.githubusercontent.com/16165385/90990187-ba6f1d80-e575-11ea-8358-2b2ddce45774.png)

- `invoice` criado com sucesso, vamos então verificar as informações

![invoice_imopay](https://user-images.githubusercontent.com/16165385/90990200-d1157480-e575-11ea-9d88-2cd9584e1de5.png)

- informações conferem, foi a descrição esta como foi definido no teste `Imobanco  - Pedido Boleto`, status `not_paid`

- vamos verificar o transaction

![transaction criado](https://user-images.githubusercontent.com/16165385/90990234-1c2f8780-e576-11ea-9452-8b92859334d2.png)

- transaction criado com sucesso, vamos verificar as informações

![transaction_boleto](https://user-images.githubusercontent.com/16165385/90990241-2cdffd80-e576-11ea-8262-e20dd9acda5d.png)

- corretamente cadastrado 

- vamos agora verificar no `dbeaver` se o pedido foi cadastrado corretamente

![boleto no dbeaver](https://user-images.githubusercontent.com/16165385/90990249-45501800-e576-11ea-83e9-14a39af74742.png)

- pedido cadastrado corretamente

**Comment by Raidro** [comment]
@rodrigondec @PedroRegisPOAR  Espero o feedback!

**Comment by Raidro** [comment]
# Re-Teste transação cartão presente

# Considerações

- O pedido foi criada com sucesso ao `finalizar compra`
- O pedido foi criada com sucesso no `minha conta`
- A transação foi criada corretamente no `imopay_api`
- O pedido foi registrado corretamente no `dbeaver`
- Todas as informações estão corretamente cadastradas

# Prints

- Com um usuário previamente criado, com endereço corretamente cadastrado, vamos então acessar a loja pela url: `localhost` e realizar a compra da faca Karambit

- na tela de carrinho ( `localhost/carrinho`) vamos então fechar a compra e prosseguir pra próxima tela

- na tela de finalizar compra (`localhost/finalizar-compra`) vamos então preencher tudo que dor necessário e finalizar a compra selecionando o método de pagamento `cartão`:

![pedido_cartao_present](https://user-images.githubusercontent.com/16165385/91049843-31e39200-e5f4-11ea-8419-d97f31862d29.png)

![detalhe_cartao_+presente](https://user-images.githubusercontent.com/16165385/91049908-4d4e9d00-e5f4-11ea-9caa-b6d7e26481d3.png)


- a compra foi finalizada com sucesso 

- vamos então olhar no `minha conta` se o pedido foi cadastrado corretamente

- na tela do minha conta, vamos clicar em `pedidos`

![visualizacao_minha_conta](https://user-images.githubusercontent.com/16165385/91049956-5fc8d680-e5f4-11ea-825a-1756e68e3efe.png)

- pedido esta registrado corretamente. vamos então clicar em visualizar 

![visualizar_pagamento_pendendte ](https://user-images.githubusercontent.com/16165385/91050029-740cd380-e5f4-11ea-8b7b-cc8fdaabadfc.png)

- todas as informações esto corretamente cadastradas no `minha conta`

- vamos olhar o `imopay_api` se a `transação` foi criada

![trasaction_imopay_api](https://user-images.githubusercontent.com/16165385/91050200-b504e800-e5f4-11ea-84a4-8dd013201a0b.png)

- foi criado a ``transaction` corretamente no `imopay_api`

- vamos então olhar se as informações estão corretamente cadastrados na `transaction`

![imopai_api_trasacton](https://user-images.githubusercontent.com/16165385/91050362-ee3d5800-e5f4-11ea-9740-5213b0291bf3.png)

- `transaction` com todas as informações corretamente cadastrados

- vamos agora olhar no `dbeaver`

![printe_dbeaver=](https://user-images.githubusercontent.com/16165385/91050465-0e6d1700-e5f5-11ea-858f-e0f79819230c.png)

- dados corretamente cadastrados no `dbeaver`

- vamos olhar nos `consoles` se no deu nenhum erro

- console `Imopay_api`

![sucesso_console](https://user-images.githubusercontent.com/16165385/91050695-69067300-e5f5-11ea-9803-e5580b5c4a94.png)

- `transação` criada com sucesso. saiu com `status 201` (criado com sucesso)

- console `debug`

![sucesso_console_debug](https://user-images.githubusercontent.com/16165385/91050779-88050500-e5f5-11ea-8d60-a007067e5c36.png)

- pedido cadastrado corretamente no `ecommerce`

**Comment by Raidro** [comment]
@rodrigondec @PedroRegisPOAR  espero o feedback!!

**Comment by rodrigondec** [comment]
Está top demais. E em transação não foi encontrado falhas no plugin.

Retirando a parte da configuração para aparecer os nomes dos métodos de pagamento.

Podemos prossegui para a próxima etapa que são os webhooks!
