### ISSUE TITLE
Testando webhook

### ISSUE THREAD

**Issue by rodrigondec** [imobanco/WooCommerce-Imobanco#18]
# Resumo
Relacionado ao épico #13.

Precisamos testar a parte do webhook da loja e sns do imopay!

Cada loja vai possuir um webhook no imopay. Então digamos que existe a loja 'oticabibi' (nome totalmente fictício).

Quando essa loja passar a existir na infra, precisará ser criado um webook no imopay com a `url = {dominio_loja.imobanco.com.br}/{endpoint_do_plugin_para_receber_notificação}`.

Essa criação deverá ser feita na mão para realizar o teste. 
> @PedroRegisPOAR ficará encarregado de analisar e pensar em formas de automatizar.

# endpoint_do_plugin_para_receber_notificação
Existe esse endpoint criado no plugin

https://github.com/imobanco/WooCommerce-Imobanco/blob/b648ed0368c25cf4e6caf5517466d628cb6949ff/woocommerce-imobanco/includes/api.php#L5

# Configuração (manual/automática)
> utilizar o ngrok para hospedar a loja de vocês no localhos
- 1. [x] criar o endpoing com a url correta da loja

# Outputs
Todos os testes precisam ser documentados nessa issue como um novo comentário da seguinte forma:

```
# Nome do teste
## Considerações
alguma consideração dos testadores caso tenha

## Prints
file_upload1
.
.
.
file_uploadn
``` 

Na sessão `## Prints` quero:
- foto da interface do usuário na loja mostrando o peido
- foto do wp-admin do pedido criado (com seus dados)
- foto do django admin com as infos do transaction/payment_method (2 fotos para boleto)
- foto do dbeaver mostrando o `id_imopay` do usuário da loja (caso seja possível ver isso no wp-admin, mostrar no wp-admin)

# 1. Confirmação do webhook
**Dado** que foi criado o webhook no imopay com a url correta
**Quando** a loja receber o request de 'ping' do SNS
**Então** a loja deve ter confirmado a própria assinatura

> a loja confirmar a assinatura é a loja fazer um request para o `SubscriptionUrlP` recebido no request de 'ping'

> confirmado a assinatura é o termo da aws. Tem que ver lá no console da AWS ou na CLI o subscription com o status 'confirmed' e que ele tenha agora o ARN

## Checklist
- [x] confirmação do webhook

# 2. Atualização do pedido
**Dado** que:
  - já foi criado o webhook
  - a assinatura já foi confirmada
  - um usuário u_loja1 na loja
  - um buyer b_imo1 para u_loja1 no imopay
  - endereço e_loja1 na loja
  - endereço e_imo1 no imopay para b_imo1
  - produto pr_loja1 na loja
  - pedido pe_loja1 do u_loja1 com o produto pr_loja1

**Quando** o u_loja1 fizer o checkout e pagamento do pe_loja1
**Então**:
  - a loja deve receber o request de atualização da transação
  - o pe_loja1 deve ter sido atualizado com base nas informações do request de atualização

## Checklist
- [x] atualização do pedido

**Comment by rodrigondec** [comment]
# Teste 1. Confirmação do webhook
## Considerações
- o zoop hook foi cadastrado manualmente no impay com o meu ngrok
- o webhook foi cadastrado manualmente no imopay com o ngrok do PC do Mateus
- a subscription foi criada na AWS
- a loja confirmou a própria subscription

## Prints

### Cadastro zoop hook
![image](https://user-images.githubusercontent.com/3301060/91057568-c0104600-e5fd-11ea-9d15-8c7266fbc832.png)

![image](https://user-images.githubusercontent.com/3301060/91057604-cdc5cb80-e5fd-11ea-8ad5-6f46419250e0.png)


### Cadastro webhook
![image](https://user-images.githubusercontent.com/3301060/91058474-e08cd000-e5fe-11ea-9f9e-db1c7baad71a.png)

![image](https://user-images.githubusercontent.com/3301060/91057672-e7ffa980-e5fd-11ea-88c8-34f1e38bed44.png)

### Confirmação da assinatura
![image](https://user-images.githubusercontent.com/3301060/91058249-9efc2500-e5fe-11ea-90f1-6521656dadea.png)


![image](https://user-images.githubusercontent.com/3301060/91058035-60ff0100-e5fe-11ea-8b29-a1a70fcf3d53.png)

**Comment by rodrigondec** [comment]
# Teste 2. Atualização do pedido
## Considerações
- o `pedido foi feito` com sucesso no **woocommerce**
- a `transação foi cadastrada` com sucesso no **imopay**
- o **imopay** recebeu a `atualização do zoophook` corretamente
- o **ecommerce** recebeu a `notificação do webook` corretamente
- o **ecommerce** atualizou o pedido de `pendente` para `aguardadndo`

## Prints
### Cadastro Buyer
Foi cadastrado corretamente o buyer

![image](https://user-images.githubusercontent.com/3301060/91058770-3e211c80-e5ff-11ea-83f3-0f94b5962734.png)

### Cadastro endereço
Foi cadastrado corretamente o address
![image](https://user-images.githubusercontent.com/3301060/91058852-598c2780-e5ff-11ea-8d36-b0e8aa7489f9.png)

### Checkout do pedido
Agora vamos realizar o pedido no ecommerce/loja!

#### Pedido woocommerce
O pedido foi feito no ecommerce
![image](https://user-images.githubusercontent.com/3301060/91059382-049ce100-e600-11ea-8005-f31b5f1da557.png)

> como podemos ver no debug
> ![image](https://user-images.githubusercontent.com/3301060/91060913-e9cb6c00-e601-11ea-8182-378163fc1029.png)



#### Transação imopay
A transação foi cadastrada no imopay com sucesso

![image](https://user-images.githubusercontent.com/3301060/91059496-2dbd7180-e600-11ea-9b41-35fe9fe9819c.png)

> como podemos ver no debug o recebimento da transação
> ![image](https://user-images.githubusercontent.com/3301060/91059467-21391900-e600-11ea-9502-10487b87e131.png)


#### Atualização zoophook
O imopay recebeu corretamente a atualização do zoop hook

![image](https://user-images.githubusercontent.com/3301060/91061410-783fed80-e602-11ea-9bc7-e5ed326cd476.png)

![image](https://user-images.githubusercontent.com/3301060/91062042-a0c7e780-e602-11ea-9c85-0791d4db101c.png)

#### Atualização webhook loja
A loja recebeu corretamente a notificação da transação atualizada

![image](https://user-images.githubusercontent.com/3301060/91059806-90af0880-e600-11ea-8aca-21f71890721c.png)

![image](https://user-images.githubusercontent.com/3301060/91060641-9527f100-e601-11ea-8425-1059c25deae4.png)

#### Pedido woocommerce
Agora vemos que nosso pedido está com o status aguardando
![image](https://user-images.githubusercontent.com/3301060/91062160-bc32f280-e602-11ea-9b50-7dc4b5207fb6.png)

> mais detalhes
> ![image](https://user-images.githubusercontent.com/3301060/91062185-c5bc5a80-e602-11ea-874b-60b077ee461e.png)

##### No WP-admin
No wp-admin podemos ver o pedido

![image](https://user-images.githubusercontent.com/3301060/91062369-fdc39d80-e602-11ea-89eb-9fb558a55f37.png)

E tem a nota de alteração do status de `pendente` para `aguardando`!
![image](https://user-images.githubusercontent.com/3301060/91062402-09af5f80-e603-11ea-9966-6572f576b27b.png)

**Comment by rodrigondec** [comment]
Esses testes possuíram resultados satisfatórios e está tudo funcional!

@jsb989

**Comment by jsb989** [comment]
Vocês são extremamente crocantes;
