### ISSUE TITLE
Configuração inicial do ambiente

### ISSUE THREAD

**Issue by rodrigondec** [imobanco/WooCommerce-Imobanco#19]
# Resumo
Relacionado ao #13.

Para a loja woocommerce estar funcionando é necessário fazer algumas configurações.

# Passos
- Seguir as instruções no [README.md do Ecommerce](https://github.com/imobanco/Ecommerce/tree/feature/testar-plugin-de-pagamento#novas-instru%C3%A7%C3%B5es-para-uso)

**Comment by PedroRegisPOAR** [comment]
@rodrigondec vou fechar essa issue, acredito que isso esteja resolvido com os comandos que fiz no make.

**Comment by PedroRegisPOAR** [comment]
## Resumo

### Estou documentando aqui todos os passos usando mais de _40 prints_ para poder se chegar ao estado do sistema necessário para poder se iniciar os testes do plugin desenvolvido pelo Bruno.

**Comment by PedroRegisPOAR** [comment]
### Print 1

![passo-1](https://user-images.githubusercontent.com/20312381/90291847-1c81a180-de57-11ea-9980-e3d9b4cbbb63.png)

**Comment by PedroRegisPOAR** [comment]
### Print 2

![passo-2](https://user-images.githubusercontent.com/20312381/90291883-2e634480-de57-11ea-920e-d9c82d2e2a75.png)

**Comment by PedroRegisPOAR** [comment]
### Print 3

![passo-3](https://user-images.githubusercontent.com/20312381/90291934-4935b900-de57-11ea-8575-9b6d42daaddb.png)

**Comment by PedroRegisPOAR** [comment]
### Print 4

![passo-4](https://user-images.githubusercontent.com/20312381/90291965-5baff280-de57-11ea-8f2a-dff616b2bfdc.png)

**Comment by PedroRegisPOAR** [comment]
### Print 5

![passo-5](https://user-images.githubusercontent.com/20312381/90292023-78e4c100-de57-11ea-8f02-a356cbea25e7.png)

**Comment by PedroRegisPOAR** [comment]
### Print 6

Fazendo um check de sanidade no navegador: [http://localhost](http://localhost)

![passo-6](https://user-images.githubusercontent.com/20312381/90292060-8bf79100-de57-11ea-9ad7-34a4b1d6d2dc.png)

**Comment by PedroRegisPOAR** [comment]
### Print 7

Checando o **admin**:

![passo-7](https://user-images.githubusercontent.com/20312381/90292145-be08f300-de57-11ea-98b4-d0feb8f65e7d.png)

**Comment by PedroRegisPOAR** [comment]
### Print 8

Indo para o admin:

![passo-8](https://user-images.githubusercontent.com/20312381/90292208-de38b200-de57-11ea-829f-848cd581a646.png)

**Comment by PedroRegisPOAR** [comment]
### Print 9

Clicar em **Run the Setup Wizard**:

![passo-9](https://user-images.githubusercontent.com/20312381/90292312-09230600-de58-11ea-8297-3ba3c60c7182.png)

**Comment by PedroRegisPOAR** [comment]
### Print 10

Clicar no **Yes please**

![passo-10](https://user-images.githubusercontent.com/20312381/90292415-38d20e00-de58-11ea-86a7-7884bd6c217a.png)

**Comment by PedroRegisPOAR** [comment]
### Print 11

![passo-11](https://user-images.githubusercontent.com/20312381/90292493-5a32fa00-de58-11ea-9a78-1df71c5f0ad9.png)

**Comment by PedroRegisPOAR** [comment]
### Print 12

![passo-12](https://user-images.githubusercontent.com/20312381/90292519-67e87f80-de58-11ea-9d76-20910ef1a53b.png)

**Comment by PedroRegisPOAR** [comment]
### Print 13

![passo-13](https://user-images.githubusercontent.com/20312381/90292537-72a31480-de58-11ea-96ec-214e865eff8e.png)

**Comment by PedroRegisPOAR** [comment]
### Print 14

![passo-14](https://user-images.githubusercontent.com/20312381/90292565-82225d80-de58-11ea-9891-8bf9c7f62d3d.png)

**Comment by PedroRegisPOAR** [comment]
### Print 15

![passo-15](https://user-images.githubusercontent.com/20312381/90292580-8b132f00-de58-11ea-93de-f000c351a796.png)

**Comment by PedroRegisPOAR** [comment]
### Print 16

![passo-16](https://user-images.githubusercontent.com/20312381/90292601-94040080-de58-11ea-84e3-6730469040dd.png)

**Comment by PedroRegisPOAR** [comment]
### Print 17

![passo-17](https://user-images.githubusercontent.com/20312381/90292624-a120ef80-de58-11ea-891e-66df7fa93356.png)

**Comment by PedroRegisPOAR** [comment]
### Print 18

![passo-18](https://user-images.githubusercontent.com/20312381/90292664-bd249100-de58-11ea-99a5-f5efc624538c.png)

**Comment by PedroRegisPOAR** [comment]
### Print 19

![passo-19](https://user-images.githubusercontent.com/20312381/90292690-c9a8e980-de58-11ea-9645-03ffd23c04bc.png)

**Comment by PedroRegisPOAR** [comment]
### Print 20

![passo-20](https://user-images.githubusercontent.com/20312381/90292704-d3325180-de58-11ea-8066-69b0970e4fcd.png)

**Comment by PedroRegisPOAR** [comment]
### Print 21

![passo-21](https://user-images.githubusercontent.com/20312381/90292727-e04f4080-de58-11ea-8196-6b75ba323179.png)

**Comment by PedroRegisPOAR** [comment]
### Print 22

![passo-22](https://user-images.githubusercontent.com/20312381/90292751-e9d8a880-de58-11ea-8cb8-d26574c9ce46.png)

**Comment by PedroRegisPOAR** [comment]
### Print 23

![passo-23](https://user-images.githubusercontent.com/20312381/90292790-fa891e80-de58-11ea-8801-bbef15de20a4.png)

**Comment by PedroRegisPOAR** [comment]
### Print 24

![passo-24](https://user-images.githubusercontent.com/20312381/90292807-04128680-de59-11ea-87e4-ff6a2a8eb527.png)

**Comment by PedroRegisPOAR** [comment]
### Print 25

Cadastrando um produto, no caso uma faca:

![passo-25](https://user-images.githubusercontent.com/20312381/90292839-168cc000-de59-11ea-9f7d-8f219217fef3.png)

**Comment by PedroRegisPOAR** [comment]
### Print 26

Adicionando o preço:

![passo-26](https://user-images.githubusercontent.com/20312381/90292872-2ad0bd00-de59-11ea-86ba-7c631ac718cd.png)

**Comment by PedroRegisPOAR** [comment]
### Print 27

![passo-27](https://user-images.githubusercontent.com/20312381/90292938-518ef380-de59-11ea-880f-c80e722cad45.png)

**Comment by PedroRegisPOAR** [comment]
### Print 28

![passo-28](https://user-images.githubusercontent.com/20312381/90292959-5d7ab580-de59-11ea-830d-1bfb7970b632.png)

**Comment by PedroRegisPOAR** [comment]
### Print 29

@phelipequeiroz acho que tem algo errado faltando nesse processo, em algum lugar talvez zapartir daqui em diante, que faz com que a imagem do produto não apareça, mas podem ser várias coisas, realemente muitas coisas ...

![passo-29](https://user-images.githubusercontent.com/20312381/90292990-6ec3c200-de59-11ea-978d-58fe517c1ee8.png)

**Comment by PedroRegisPOAR** [comment]
### Print 30

![passo-30](https://user-images.githubusercontent.com/20312381/90293109-b2b6c700-de59-11ea-9cf5-071d7a1e08e8.png)

**Comment by PedroRegisPOAR** [comment]
### Print 31

![passo-31](https://user-images.githubusercontent.com/20312381/90293123-c104e300-de59-11ea-983b-2d870654b1f8.png)

**Comment by PedroRegisPOAR** [comment]
### Print 32

@phelipequeiroz note que tem algo errado com esse css (eu acho que é o css, não sei). Tem texto ficando por cima de texto.

![passo-32](https://user-images.githubusercontent.com/20312381/90293144-ceba6880-de59-11ea-905a-f8a690d95968.png)

**Comment by PedroRegisPOAR** [comment]
### Print 33

@phelipequeiroz tem algo quebrado com o popup do whatsapp, não sei o que é.

![passo-33](https://user-images.githubusercontent.com/20312381/90293320-34a6f000-de5a-11ea-81c0-30f347553bce.png)

**Comment by PedroRegisPOAR** [comment]
### Print 34

@phelipequeiroz mais coisa quebrada no css (imagino, não tenho certeza).

![passo-34](https://user-images.githubusercontent.com/20312381/90293413-61f39e00-de5a-11ea-84a7-dffcc8e8d5f1.png)

**Comment by PedroRegisPOAR** [comment]
### Print 35

Só por completudo mostro a tela na parte de baixo.

![passo-35](https://user-images.githubusercontent.com/20312381/90293482-8780a780-de5a-11ea-9bd7-1b7cbe9e42fe.png)

**Comment by PedroRegisPOAR** [comment]
### Print 36

Buscando pela faca:

![passo-36](https://user-images.githubusercontent.com/20312381/90293576-cca4d980-de5a-11ea-952f-58661415064c.png)

**Comment by PedroRegisPOAR** [comment]
### Print 37

Faca encontrada, mas não aprece a imagem. Porque? @phelipequeiroz 

![passo-37](https://user-images.githubusercontent.com/20312381/90293618-e34b3080-de5a-11ea-8122-9698f1756aa6.png)

**Comment by PedroRegisPOAR** [comment]
### Print 38

Após clicar no link que leva para a faca. A imagem ainda não aparece @phelipequeiroz 

![passo-38](https://user-images.githubusercontent.com/20312381/90293670-037aef80-de5b-11ea-8bfe-b51415e7c092.png)

**Comment by PedroRegisPOAR** [comment]
### Print 39

#### Este passo é muito importante para o teste do plugin

Tudo o que for feito e configurado até esse ponto será salvo de forma a possibilitar que após se "bagunçar" seja possivel que se restaure o estado dos passo feitos manualmente.

![passo-39](https://user-images.githubusercontent.com/20312381/90293751-2dccad00-de5b-11ea-86ef-a78480910426.png)

**Comment by PedroRegisPOAR** [comment]
### Print 40

Continuação da execução do comando

![passo-40](https://user-images.githubusercontent.com/20312381/90293916-9582f800-de5b-11ea-917b-aabb8bcd9d94.png)

**Comment by PedroRegisPOAR** [comment]
### Print 41

E agora pode-se "bagunçar" a vontade.

Note que as demais instruções estão no [README.md do Ecommerce](https://github.com/imobanco/Ecommerce/tree/feature/testar-plugin-de-pagamento#novas-instru%C3%A7%C3%B5es-para-uso).

Por completude vou colocar aqui tb, sempre que se quiser voltar ao estado atual executar:

`make restart.backup`

![passo-41](https://user-images.githubusercontent.com/20312381/90293948-a92e5e80-de5b-11ea-849e-14b5688990e9.png)

**Comment by phelipequeiroz** [comment]
### Respondendo as perguntas. 

# Isso não é erro de CSS
Explicando:
Quase todos os menus de rolagem tem a função de carregar por cima do conteúdo numa questão chamada de Z-index. Dá mesma forma que o github tem nível de branchs diferente ou está abaixo ou acima como também está na mesma branch. Tendeu? 
![image](https://user-images.githubusercontent.com/54398717/90327091-745afe00-df66-11ea-829e-4cdc71a6c9b0.png)

# Imagem Upload
Se a imagem que voce fez o upload for selecionado é para aparecer tanto na página principal como na página do produto e é algo que já funcionou por diversas vezes. Nesse caso, eu acredito que seja apenas um erro de execução. 
![image](https://user-images.githubusercontent.com/54398717/90327204-9a34d280-df67-11ea-8f98-5eaf71324987.png)

# Whatsapp

O erro pode ser apenas de configuração e também escolhar o perfil de estilo. 
![image](https://user-images.githubusercontent.com/54398717/90327225-bf294580-df67-11ea-80f8-a5b5e2a503ea.png)

**Comment by rodrigondec** [comment]
Com os questionamentos sobre o CPF faltando do #15 recebi o feedback do @ibrunodev 

![image](https://user-images.githubusercontent.com/3301060/90573268-6981b280-e18c-11ea-9ed3-0a9469a95e52.png)

**Comment by PedroRegisPOAR** [comment]
## Adicionando o plugin: woocommerce-extra-checkout-fields-for-brazil

Página do plugin:
https://br.wordpress.org/plugins/woocommerce-extra-checkout-fields-for-brazil/

Por algum motivo, que não sei qual, o nome do plugin é:
`woocommerce-extra-checkout-fields-for-brazil`

Ou seja, o fim da url:

https://github.com/claudiosanches/woocommerce-extra-checkout-fields-for-brazil

**Comment by rodrigondec** [comment]
Foi trocado o container à alguns dias atŕas. E alteramos a maneira de automatizar o setup. Fechando esse issue!
